# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: advent-of-code-2019"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advent-of-code-2019
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advent-of-code-2019
  template:
    metadata:
      labels:
        app: advent-of-code-2019
    spec:
      containers:
      - name: server
        image: advent-of-code-2019
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"